//category
export const CATEOGRY_GENERAL_STATE = 'CATEOGRY_GENERAL_STATE';
export const CATEGORY_TASK_REORDER_STATIC = 'CATEGORY_TASK_REORDER_STATIC';
export const CATEGORY_TASK_UPDATE_STATIC = 'CATEGORY_TASK_UPDATE_STATIC';
export const CATEGORY_TASK_DELETE_STATIC = 'CATEGORY_TASK_DELETE_STATIC';
export const CATEGORY_CREATE_STATIC = 'CATEGORY_CREATE_STATIC';
export const CATEGORY_TASK_STATIC = 'CATEGORY_TASK_STATIC';


//task
export const TASK_GENERAL_STATE = 'TASK_GENERAL_STATE';
export const TASK_DELETE_STATE = 'TASK_DELETE_STATE';

